C++11: ptr_fun.h: Replace generated ptr_fun1/2/3/etc with ptr_fun<>.
Note that T_Return must now be the first parameter, so that the
variadic template parameters may be trailing, and this means that
the return type must now be specified if you specify any argument
types.
For instance:
  ptr_fun<type_arg1>(&somefunc)
now becomes
  ptr_fun<void, type_arg2>(&somefunc)

and
  ptr_fun<type_arg1, type_return>(&somefunc)
now becomes
  ptr_fun<type_return, type_arg1>(&somefunc)

which might be an annoying API change, even though most people just
use ptr_fun().

However, this breaks the tests:

test_ptr_fun.cc: In function ‘int main(int, char**)’:
test_ptr_fun.cc:64:21: error: no matches converting function ‘foo’ to type ‘void (*)()’
   sigc::ptr_fun(&foo)();
                     ^
test_ptr_fun.cc:24:6: note: candidates are: void {anonymous}::foo(int)
 void foo(int i1)
      ^
test_ptr_fun.cc:18:5: note:                 int {anonymous}::foo()
 int foo()
     ^